# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
#env = GDK_SCALE,2
#monitor=,preferred,auto,auto

# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.6

# Straight 1x setup for low-resolution displays like 1080p or 1440p
env = GDK_SCALE,1
monitor=,preferred,auto,1

# MONITOR VARIABLES - `hyprctl monitors`
$MONITOR_PRIMARY = desc:LG Electronics LG ULTRAGEAR+ 408NTPCCZ200
$MONITOR_SECONDARY = desc:Philips Consumer Electronics Company PHL 230B8Q 0x00000035
$MONITOR_TERTIARY_SOURCE = desc:LG Display 0x0709
$MONITOR_TERTIARY = desc:Invalid Vendor Codename - RTK WIMAXIT 0x01010101

# Layout con monitor principale a sinistra e secondario a destra (coerente con hyprmonitor)
$PRIMARY_POS = 0x0

#$SECONDARY_POS = 3440x0
#$SECONDARY_POS = 2560x0
$SECONDARY_POS = 3440x0
$TERTIARY_POS = 0x1440


# MONITORS (posizioni da `hyprctl monitors` / hyprmonitor)
monitor=$MONITOR_PRIMARY,3440x1440@240.09,$PRIMARY_POS,1
monitor=$MONITOR_SECONDARY,preferred,auto,1,transform,1
monitor=$MONITOR_TERTIARY_SOURCE,preferred,$TERTIARY_POS,1
monitor=$MONITOR_TERTIARY,preferred,$TERTIARY_POS,1,mirror,$MONITOR_TERTIARY_SOURCE

# WORKSPACE RULES: limita workspace ai soli specificati, settare specifico layout layoutopt:wslayout-layout:dwindle
workspace = 1, monitor:$MONITOR_PRIMARY, persistent:true
workspace = 2, monitor:$MONITOR_PRIMARY, persistent:true
workspace = 3, monitor:$MONITOR_PRIMARY, persistent:true, default:true
workspace = 4, monitor:$MONITOR_PRIMARY, persistent:true
workspace = 5, monitor:$MONITOR_PRIMARY, persistent:true
workspace = 6, monitor:$MONITOR_SECONDARY, persistent:true
workspace = 7, monitor:$MONITOR_SECONDARY, persistent:true
workspace = 8, monitor:$MONITOR_SECONDARY, persistent:true
workspace = 9, monitor:$MONITOR_TERTIARY_SOURCE, persistent:true
workspace = 10, monitor:$MONITOR_TERTIARY_SOURCE, persistent:true
workspace = 11, monitor:$MONITOR_TERTIARY_SOURCE, persistent:true
