# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# narch laptop panel from `hyprctl monitors`:
# Monitor eDP-1: LG Display 0x062E, 1920x1080@59.977
env = GDK_SCALE,1

$MONITOR_PRIMARY = eDP-1
$PRIMARY_POS = 0x0

monitor=$MONITOR_PRIMARY,1920x1080@59.98,$PRIMARY_POS,1

# WORKSPACE RULES: laptop single-screen setup
workspace = 1, monitor:$MONITOR_PRIMARY, persistent:true
workspace = 2, monitor:$MONITOR_PRIMARY, persistent:true
workspace = 3, monitor:$MONITOR_PRIMARY, persistent:true, default:true
workspace = 4, monitor:$MONITOR_PRIMARY, persistent:true
workspace = 5, monitor:$MONITOR_PRIMARY, persistent:true
